### PR TITLE
GitHub Action to run cpplint on pushes & pull requests

### PR DESCRIPTION
**Pull request by cclauss**
This is a much simpler solution that loads quickly but does not require a custom Dockerfile.

### CODE REVIEW

**Review by tkruse — APPROVED** [review]
LGTM.  I am not an expert on actions so I would not spot a bug by reviewing, though.

**Comment by tkruse** [comment]
feel free to merge. I leave it to you in case you are experimenting.

**Comment by peternewman** [comment]
It would probably now make sense to convert this to a composite action, so people can benefit from any potential internal improvements to the action such as annotations, without them having to manually update what's effectively currently a workflow template:
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

**Comment by tkruse** [comment]
@peternewman : I am not up-to-date with github actions, and there is a lot to read. Do you have any current obviously beneficial example for how composite action would improve user experience with this action?

**Comment by cclauss** [comment]
Also, the billing implications of using composite actions?

**Pull request merged**
